# Set the project name to the current directory name
# For example, if the path is /Users/foo/beep8-sdk/sample/hello,
# then "hello" will be assigned to $(PROJECT)
PROJECT := $(notdir $(CURDIR))

# Uncomment the following line to enable .lst (assembly listing) file generation.
# This will slightly increase the build time due to the extra output step.
# EXPORT_LIST = 1

# Include the common application Makefile
# This file contains shared build rules and toolchain settings
include	../makefile.app
