name: Publish docs/index.md to DEV.to

on:
  push:
    paths:
      - 'docs/index.md'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish to DEV.to
        uses: sinedied/publish-devto@v1
        with:
          devto_key: ${{ secrets.DEVTO_API_KEY }}
          files: docs/index.md
